"""create pins table

Revision ID: 1c0334f64e38
Revises: dfb329701799
Create Date: 2026-09-09 16:04:39.449561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0334f64e38'
down_revision: Union[str, Sequence[str], None] = 'dfb329701799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('tagged_products', sa.JSON(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('mark_as_ai_modified', sa.Boolean(), nullable=False),
    sa.Column('includes_ai_generated_person', sa.Boolean(), nullable=False),
    sa.Column('allow_comments', sa.Boolean(), nullable=False),
    sa.Column('show_similar_products', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pins_id'), 'pins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pins_id'), table_name='pins')
    op.drop_table('pins')
    # ### end Alembic commands ###
