"""add username to users

Revision ID: 36487e804173
Revises: b727aa762c13
Create Date: 2026-09-15 10:59:49.387403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36487e804173'
down_revision: Union[str, Sequence[str], None] = 'b727aa762c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. add as nullable first
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))

    # 2. backfill existing rows with something unique (derived from email)
    connection = op.get_bind()
    users = connection.execute(sa.text("SELECT id, email FROM users")).fetchall()
    for user_id, email in users:
        fallback_username = email.split("@")[0]
        connection.execute(
            sa.text("UPDATE users SET username = :username WHERE id = :id"),
            {"username": fallback_username, "id": user_id},
        )

    # 3. now enforce NOT NULL + unique index
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('username', nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
