"""add status to pins

Revision ID: b727aa762c13
Revises: 1c0334f64e38
Create Date: 2026-09-11 11:45:51.480689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b727aa762c13'
down_revision: Union[str, Sequence[str], None] = '1c0334f64e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('status', sa.String(), nullable=False, server_default='draft'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pins', 'status')
    # ### end Alembic commands ###
